version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    restart: always

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    restart: always

  user-service:
    build: ./user-service
    ports:
      - "5002:5002"
    restart: always

  parking-slot-service:
    build: ./parking-slot-service
    ports:
      - "5003:5003"
    restart: always
