apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: yourdockerhubusername/auth-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/parking
        - name: PORT
          value: "5001"
        - name: JWT_SECRET
          value: rahasiaSuperAman123
